# Generated by Django 6.1.1 on 2026-09-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('single', 'Single Rooms'), ('flat', '4 bhk Flat Rooms'), ('double', 'Double Rooms')], max_length=100)),
                ('category', models.CharField(choices=[('premium', 'Premium Rooms'), ('standard', 'Standard Rooms'), ('budget', 'Budget Rooms'), ('hostel', 'Hostel Rooms'), ('pg', 'PG Rooms'), ('flat', 'Flat Rooms')], max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_img/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='rooms.room')),
            ],
        ),
    ]
